### ISSUE TITLE
스켈레톤 코드에서의 생성자와 소멸자 이름이 다를 때

### ISSUE THREAD

**Issue by coreabosun** [jisanggeun/DS_Project2_2024_2#1]
public:
	FlightData() {
		AirlineName = "";
		FlightNumber = "";
		Destination = "";
		Seats = 99;
		Status = "";
	}
	~VaccinationData() {

	}
	
위와 같이 스켈레톤 코드에서 FlightData 클래스의 생성자와 소멸자의 이름이 다른데 소멸자의 이름을 바꿔도 괜찮을까요

**Comment by jisanggeun** [comment]
수정했습니다. 

감사합니다.
