### ISSUE TITLE
ADD 명령어 관련해서 질문드립니다

### ISSUE THREAD

**Issue by DwKwCs** [jisanggeun/DS_Project2_2024_2#10]
1. ADD 명령에서 좌석 수를 감소시키는 기준
운항 상태 정보가 4가지(Departure, Boarding, Delayed, Cancelled)일 때, ADD 명령어에서 상태에 따라 좌석 수를 1 감소시킬지 여부를 결정한다고 했습니다. 
여기서 좌석 수를 감소시키는 상태는 Boarding과 Delayed라고 위에 명시되어있는데, ADD 명령어 실행 시에 기존의 운항 상태를 따라서 기존 운항 상태가 Boarding 또는 Delayed일 때 좌석 수를 감소시켜야 하는 지, ADD 명령어로 업데이트하는 운항 상태가 Boarding 또는 Delayed일 때 좌석 수를 감소시켜야 하는 지 궁금합니다.
ex) 기존 상태 : Departure, ADD 명령어 : Delayed 일 때 좌석 수가 1 감소되는 것이 맞는지.
기존 상태 : Boarding, ADD 명령어 : Departure 일 때 좌석 수가 1 감소되지 않는 것이 맞는지.

2. 상태 정보 업데이트 기준
ADD 명령어로 운항 상태를 업데이트할 때, 상태 정보가 업데이트되는 기준이 궁금합니다.
기존의 운항 상태에 관련없이 어떤 운항 상태에 대해서도 업데이트를 하는 지, 아니면 1) 기존 운항 상태가 Cancelled이고, ADD 명령어로 인해 운항 상태가 Boarding으로 업데이트 될 때, 2) 기존 운항 상태가 Boarding이고, ADD 명령어로 인해 운항 상태가 Cancelled로 업데이트 될 때 만을 말하는지 궁금합니다.

3. 에러 코드 출력의 경우의 수
ADD 명령어의 에러 코드 출력 부분에서 '항공편의 상태가 Cancelled 또는 Departure일 때, 상태를 바꾸지 않고 ADD 명령어를 수행할 경우' 라고 되어 있는데 '상태를 바꾸지 않는'이라는 문장의 뜻이 기존의 운항 상태와 같은 운항 상태가 들아와서 상태가 바뀌지 않을 때를 말하는지 궁금합니다.
ex) 기존 상태 : Cancelled, ADD 명령어 : Cancelled 일 때 상태가 바뀌지 않았으므로 에러 코드를 출력하는 것이 맞는 지.

4. ADD 명령어의 실행 결과 형식
ADD 명령어 실행 성공 시 출력 형식은 업데이트된 정보를 출력하는 것이 맞는 지 궁금합니다.

**Comment by jisanggeun** [comment]
1. Cancelled --> Boarding과 Boarding --> Boarding, Delayed --> Delayed만 좌석 수가 1 감소됩니다.
나머지 경우에는 좌석 수가 감소 안된다고 보시면 됩니다. 

또한, 상태 업데이트는 Cancelled --> Boarding, Boarding --> Cancelled만 가능합니다.
(Delayed--> Boarding 불가능, Boarding-->Delayed 불가능)

따라서 주어진 예제는 애초에 불가능한 조건입니다.

**Comment by DwKwCs** [comment]
답변 감사합니다.
