### ISSUE TITLE
ADD 관련 질문입니다.

### ISSUE THREAD

**Issue by cssrex** [jisanggeun/DS_Project2_2024_2#13]
(기존 상태) -> (입력으로 들어온 상태) 라고 할 때

Canceled -> boarding
Boarding -> boarding
Delayed -> delayed
3가지는 좌석 수 1 감소,

Boarding canceled
1가지는 좌석 수 유지

그 외 모든 경우의 상태 (Departure -> Departure 등)은 오류 메시지를 출력하는 게 맞을까요?

추가로 항공편명은 항상 숫자와 대문자알파벳의 조합으로 5자리, 도착지명은 항상 대문자 알파벳 3자리(JEJU 항공사는 CJU 고정)라고 되어 있는데, 이렇지 않은 입력은 안 들어온다고 생각해도 되는것인지, 아니면 들어왔을때 예외처리를 해서 무시해야 하는건지 궁금합니다.

**Comment by jisanggeun** [comment]
1. 오류 메세지 관련 조건 PDF에 업데이트 했습니다. (그 외 모든 경우의 상태 (Departure -> Departure 등)은 오류 메시지를 출력하는 게 맞습니다.)

2. 항공편명의 경우 중복은 없으며, 제주 항공의 경우 도착지가 CJU로 고정이 되어 있는데, 이 부분에 대해선 타 지역이 들어왔을 땐 예외 처리 하셔야 합니다.

감사합니다.
