### ISSUE TITLE
LOAD 명령어에서 제주 항공편 관련 질문있습니다.

### ISSUE THREAD

**Issue by DwKwCs** [jisanggeun/DS_Project2_2024_2#14]
제주 항공의 도착지는 CJU로 고정되어 있습니다. 이때, 제주 항공의 도착지가 CJU가 아닌 다른 도착지일 경우에 LOAD 명령어에서는 이 데이터를 삽입하지 않고 다음 데이터를 삽입하는지, 아니면 에러가 발생해서 LOAD 명령어가 에러코드를 출력해야 하는지 궁금합니다.
추가로 항공사 별 탑승 가능 좌석 수도 정해진 대로 안 들어오는 경우도 고려해야 하는지 궁금합니다.

**Comment by jisanggeun** [comment]
1. 항공편명의 경우 중복은 없으며, 제주 항공의 경우 도착지가 CJU로 고정이 되어 있는데, 이 부분에 대해선 타 지역이 들어왔을 땐 예외 처리 하셔야 합니다.
2. 고려하셔야 합니다.
