### ISSUE TITLE
VLOAD 명령어 관련 질문있습니다.

### ISSUE THREAD

**Issue by DwKwCs** [jisanggeun/DS_Project2_2024_2#15]
VLOAD 명령어는 AVL 트리에서 재귀를 사용하지 않고 Queue, Stack STL을 사용해서 데이터를 불러온다고 했습니다. 이때, Queue, Stack 둘다 사용해야 하는지 아니면 둘 중 원하는 것 하나만 사용해서 구현해도 되는지 궁금합니다.

**Comment by jisanggeun** [comment]
원하는 것 하나만 사용해서 구현하시면 되겠습니다.
