### ISSUE TITLE
LOAD 명령어 관련 질문

### ISSUE THREAD

**Issue by Hagyeong13** [jisanggeun/DS_Project2_2024_2#17]
LOAD -> ADD -> 다른 명령어 순으로 진행할 경우, 
LOAD를 할 때 input.txt에 조건을 만족하지 못하는 항공권 정보가 존재할 경우 그 전이나 그 이후 값들도 다 LOAD 되지 못하여 B+ Tree가 비어있는 상태가 되나요?
또한, 제시된 반환형 변경해도 되나요?

**Comment by Hagyeong13** [comment]
또한 <LOAD는 command.txt의 첫번째 줄에 한 번만 사용된다.>고 functional Requirements에 제시되어 있는데,
무조건 LOAD는 command.txt의 첫번째 줄에만 있다고 가정하는 건가요 아니면 예외처리를 따로 해주어야하나요? 
예외처리가 필요한 경우엔(첫번째 줄에 LOAD가 오지 않을 경우나, 중간에 LOAD가 오는 경우 등 이럴 경우 등) 에러코드 800을 출력하나요? 아니면 100을 출력해야하나요?

**Comment by jisanggeun** [comment]
1. LOAD -> ADD -> 다른 명령어 순으로 진행할 경우,
LOAD를 할 때 input.txt에 조건을 만족하지 못하는 항공권 정보가 존재할 경우 그 전이나 그 이후 값들도 다 LOAD 되지 못하여 B+ Tree가 비어있는 상태가 되나요? 

--> 맞습니다. B+ Tree가 비어있는 상태입니다.

또한, 제시된 반환형 변경해도 되나요?

--> 제시된 반환형 변경하셔도 됩니다.

**Comment by Hagyeong13** [comment]
매개변수 변경도 가능한가요?

**Comment by jisanggeun** [comment]
프로젝트 형식에 위배되지 않는 선에서 매개변수 변경도 가능합니다.
