### ISSUE TITLE
ADD 명령어 관련 질문드립니다

### ISSUE THREAD

**Issue by hanasol** [jisanggeun/DS_Project2_2024_2#18]
제안서에 좌석 수가 0인 항공편은 더 이상 동일한 항공편을 받지 않고 상태를 업데이트하지 않는다고 되어있는데, 좌석 수가 0인 항공편이 ADD 명령어로 들어오면 에러를 출력해야는지 아무것도 업데이트 되지 않은 상태를 출력해야하는지 질문드립니다.

**Comment by jisanggeun** [comment]
좌석 수가 0인 항공편이 ADD 명령어로 들어오는 것은 테스트케이스에 포함되어 있지 않기 때문에,

고려 안 하셔도 될 것 같습니다. 

감사합니다.
