### ISSUE TITLE
항공편명 자리수

### ISSUE THREAD

**Issue by hanasol** [jisanggeun/DS_Project2_2024_2#2]
제안서에서 항공편명은 대문자+숫자를 조합하여 6자리라고 되어있는데 텍스트 파일의 예시와 트리의 예시는 모두 5자리로 나와있습니다. 어떤게 맞는건가요 ?

**Comment by jisanggeun** [comment]
알파벳 + 숫자 조합 5자리로, 예시가 맞습니다. 

제안서 빠르게 수정했습니다. 

감사합니다.
