### ISSUE TITLE
제출 관련 질문입니다.

### ISSUE THREAD

**Issue by cssrex** [jisanggeun/DS_Project2_2024_2#21]
Code의 how to make tar.gz 부분에서는 Makefile이 포함 되어 있고,  2024_DS_Project2_v5에서는 확장자가 .cpp, .h, .pdf 이외의 파일을 제출하면 감점이라고 되어있는데 Makefile은 같이 압축하면 되나요? 아니면 하면 안되나요?

**Comment by jisanggeun** [comment]
수정했습니다.

Makefile 빼고 하시면 되겠습니다.
