### ISSUE TITLE
입출력 포맷 관련 질문

### ISSUE THREAD

**Issue by choehyeonjin** [jisanggeun/DS_Project2_2024_2#22]
command.txt에 인자가 있는 경우 탭문자로 구분하고,
log.txt에는 탭이 아닌 띄어쓰기로 구분해 출력하면 될까요?

**Comment by jisanggeun** [comment]
1. 명령어에 인자가 존재하는 경우 “\t”(탭)으로 구분합니다.
2. 'Space' + '|' + 'Space'로 구분 하시면 되겠습니다.
