### ISSUE TITLE
printErrorCode 함수 관련 문의

### ISSUE THREAD

**Issue by parkwonkuku** [jisanggeun/DS_Project2_2024_2#23]
1. 스켈레톤 코드에는 해당 함수가 아래와 같이 작성되어있습니다.

void Manager::printErrorCode(int n) {
	ofstream fout;
	fout.open("log.txt", ofstream::app);
	fout << "========== ERROR ==========" <<endl;
	fout << n << endl;
	fout << "===========================" << endl << endl;
	fout.close();
}

그런데 이런식으로 하려면 성공 메시지를 출력하는 부분에서 파일 끝에서 열고 닫는 코드를 반복적으로 작성해야 하므로 코드 중복이 발생하여 비효율적인데 printErrorCode에서 열고 닫는 코드를 지워도 되는지 궁금합니다.

2. command.txt의 인자를 탭키로 구분한다고 했는데 명령어 이후에 탭키를 입력하면 스페이스 1~4번까지 다양하게 탭키가 입력되는데 원래 이런게 맞는건지 궁금합니다.

**Comment by jisanggeun** [comment]
1. 네 바꾸셔도 됩니다.

2. '\t' 에 대한 처리를 해주셔야 합니다. 스페이스와 다릅니다.

감사합니다.
