### ISSUE TITLE
EXIT 에러코드 출력 문의

### ISSUE THREAD

**Issue by Hagyeong13** [jisanggeun/DS_Project2_2024_2#25]
Requirements in Implementation에 명령어에 인자가 모자라거나 필요 이상으로 입력 받을 시 에러 코드를 출력한다고 작성되어 있는데 EXIT 명령어도 해당되는 내용인지 궁금합니다.
EXIT 명령어는 인자가 존재하지 않는데, 인자를 받았을 경우 에러코드를 출력해야하나요?
해야한다면 EXIT 명령어의 에러코드는 따로 존재하지 않는데 잘못된 명령어인 800을 출력하면 되는건지 궁금합니다.

**Comment by jisanggeun** [comment]
EXIT 명령어 역시 예외처리 해주시길 바랍니다.

감사합니다.

**Comment by Hagyeong13** [comment]
800을 출력하면 되나요?
또한 메모리 누수 때문에 #include <memory>에 있는 스마트 포인터(std::shared_ptr)를 사용하고 싶은데 가능한지 궁금합니다.

**Comment by Hagyeong13** [comment]
또한,  명령어에 인자가 모자라거나 필요 이상으로 입력 받을 시 에러 코드를 출력에서 각각 명령어에 해당하는 에러코드를 출력하는게 맞는지도 궁금합니다. 
ex) ADD 3의 경우 300 출력인지 800 출력인지

**Comment by jisanggeun** [comment]
제안서 살펴보니 EXIT 명령어에 대한 에러코드가 없는 것을 확인해서, 그냥 테스트 케이스에서 제외하겠습니다.
EXIT 명령어에 대해선 예외처리 하실 필요없습니다.

스마트 포인터의 경우 사용 불가능합니다.
