### ISSUE TITLE
명령어 관련 질문

### ISSUE THREAD

**Issue by songhye0u0** [jisanggeun/DS_Project2_2024_2#28]
명령어에 인자(Parameter)가 모자라거나 필요 이상으로 입력 받을 시 에러 코드를 출력한다. 라고 명시되어 있는데 이러한 경우는 잘못된 명령어(800)로 봐야 하는 건가요?

**Comment by jisanggeun** [comment]
제안서 살펴보니 EXIT 명령어에 대한 에러코드가 없는 것을 확인했습니다.
따라서, 테스트 케이스에서 제외하도록 하겠습니다.
--> EXIT 명령어에 대해선 예외처리 하실 필요없습니다. 혼동 드린 점 죄송합니다.

**Comment by songhye0u0** [comment]
1. 항공사명이 잘못 들어왔을 때도 예외처리를 해야할까요? ex ) WrongAir

**Comment by jisanggeun** [comment]
1. 네 5개 항공사 제외 다른 항공사의 경우 예외처리 하셔야 합니다.
2. 항공편명이 5글자가 아닌 경우 예외처리 하셔야 합니다. (중복인 경우는 고려X)
3. 도착지명 역시 대문자, 소문자, 3글자 예외처리 하셔야 합니다. 
4. LOAD할 때 좌석 수가 0인 경우는 고려하지 않습니다.
5. 예외처리 하셔야 합니다.
6. 네 맞습니다. 예외처리 하셔야합니다. 대신 EXIT 명령만 예외처리 안하셔도 됩니다.
7. LOAD할 때, 항공편명 , 항공사명, 도착지명 이 같은 것은 고려 안하셔도 됩니다.
