### ISSUE TITLE
ADD 명령어 관련해서 질문있습니다.

### ISSUE THREAD

**Issue by seolbea** [jisanggeun/DS_Project2_2024_2#30]
manager 클래스의 ADD 명령어의 매개 변수가 존재하지 않던데 혹시 추가해도 되나요?

**Comment by seolbea** [comment]
1. Cancelled → Boarding, Boarding → Boarding, Delayed → Delayed, Boarding → Cancelled의 경우들만 상태 업데이트를 진행하는데 전자가 기존 상태이고 후자가 ADD 명령어에 있는 상태인 건가요?
2. 그리고 왜 Cancelled → Boarding 좌석 수를 1 감소시는 것이고 Boarding → Cancelled는 좌석 수가 변하지 않는 건가요?
3. 그리고 Boarding → Boarding, Delayed → Delayed는 좌석 수를 증가시키진 않나요?

**Comment by jisanggeun** [comment]
추가하셔도 됩니다.
1. 네 맞습니다.
2. 그건 문제 조건입니다.
3. Cancelled --> Boarding과 Boarding --> Boarding, Delayed --> Delayed만 좌석 수가 1 감소됩니다.
나머지 경우에는 좌석 수가 감소 안된다고 보시면 됩니다.
