### ISSUE TITLE
ADD 명령어 관련 질문

### ISSUE THREAD

**Issue by Hagyeong13** [jisanggeun/DS_Project2_2024_2#31]
<과제 제안서>
좌석 수가 0인 항공편의 경우, AVL Tree에 추가하고, 더 이상 동일한 항공편을 받지 않는다. (상태 정보 또한 업데이트 하지 않는다.)

[에러 코드 출력] B+Tree에 추가하려는 항공편의 자리가 없는 경우

<깃허브 질문 답변>
<img width="532" alt="ADD 관련 git 질문 답변" src="https://github.com/user-attachments/assets/094c93a6-1241-4594-aaa5-b737778d9b48">

질문 1. git 질문 답변으로는 좌석 수가 0인(자리가 없는 경우) 고려하지 않아도 된다고 하는데 과제 제안서처럼 에러 코드를 출력하여야 할 지 고려하지 않아도 될 지 답변 부탁드립니다. 감사합니다.

**Comment by jisanggeun** [comment]
제안서대로 에러코드 예외처리 하시는 게 원칙적으로는 맞습니다.

**Comment by Hagyeong13** [comment]
SEARCH_BP 명령어의 인자로 2개(시작 단어, 끝 단어)가 입력되는 경우, 범위 검색의 결과를 출력한다.
예를 들어, 인자로 C와 K가 입력되는 경우 C로 시작되는 항공편부터 K로 시작하는 항공편까지 모두 출력한다.

[에러 코드 출력]
-해당하는 항공편이 없는 경우

만약 Z,B가 인자로 입력되면 Z-B(끝 단어가 알파벳 순서상 앞일 경우)로 시작되는 항공편들을 출력해야하나요? 아니면 에러코드를 출력하면 되나요? 고려하지 않아도 되나요?

**Comment by jisanggeun** [comment]
고려하지 않으셔도 됩니다.
