### ISSUE TITLE
헤더파일에 함수 추가해도되나요?

### ISSUE THREAD

**Issue by hj-ta** [jisanggeun/DS_Project2_2024_2#32]
1. 제공된 스켈레톤 코드 중 헤더파일에 기존에 있던 함수 말고 , 새로운 함수를 추가해도 되나요? 

2. 기존의 함수의 이름이나 반환형을 바꾸면 안된다고 알고있는데, 함수 중간에 override 나 const 를 추가하는것 역시 안되는거겠죠?

**Comment by jisanggeun** [comment]
1. 추가하실 함수의 헤더를 말해주세요

2. 하셔도 됩니다.

**Comment by hj-ta** [comment]
BpTreeNode.h , BpTreeDataNode.h , BpTreeIndexNode.h 입니다
각각의 헤더파일 내의 class 에 함수를 선언하려고 합니다

**Comment by hj-ta** [comment]
그리고 FlightData.h 에 <iostream> 헤더파일이 있던데, 혹시 출력에 대한 새로운 함수를 만들어도 되나요?
아니면 run함수에만 가능한가요?

**Comment by jisanggeun** [comment]
BpTreeNode.h , BpTreeDataNode.h , BpTreeIndexNode.h 입니다
각각의 헤더파일 내의 class 에 함수를 선언하려고 합니다

--> 하셔도 됩니다.

그리고 FlightData.h 에 헤더파일이 있던데, 혹시 출력에 대한 새로운 함수를 만들어도 되나요?
아니면 run함수에만 가능한가요?

--> 새로운 함수 만드셔도 됩니다.
