### ISSUE TITLE
헤더파일에 함수 추가해도 되나요?

### ISSUE THREAD

**Issue by hj-ta** [jisanggeun/DS_Project2_2024_2#33]
헤더파일은
BpTreeNode.h , BpTreeDataNode.h , BpTreeIndexNode.h 입니다
각각의 헤더파일 내의 class 에 함수를 선언하려고 합니다.

그리고 FlightData.h 에 헤더파일이 있던데, 혹시 출력에 대한 새로운 함수를 만들어도 되나요?
아니면 run함수에만 가능한가요?

**Comment by hj-ta** [comment]
BpTree.h 에 는 가능한지 질문드립니다!

**Comment by jisanggeun** [comment]
BpTreeNode.h , BpTreeDataNode.h , BpTreeIndexNode.h 입니다
각각의 헤더파일 내의 class 에 함수를 선언하려고 합니다

--> 하셔도 됩니다.

그리고 FlightData.h 에 헤더파일이 있던데, 혹시 출력에 대한 새로운 함수를 만들어도 되나요?
아니면 run함수에만 가능한가요?

--> 새로운 함수 만드셔도 됩니다.
