### ISSUE TITLE
ADD, LOAD 명령어 및 상태 정보, 좌석 수 update 질문

### ISSUE THREAD

**Issue by anseonghwan** [jisanggeun/DS_Project2_2024_2#34]
<img width="454" alt="image" src="https://github.com/user-attachments/assets/221fb542-c9a5-455a-8384-e663704bc0d0">
과제 제안서의 상태 정보에 대한 설명으로는 위 사진처럼 명시되어 있고, 
<img width="543" alt="image" src="https://github.com/user-attachments/assets/69f0cd9f-666f-4659-8e1e-cd89eccdb159">
Bp Tree에 ADD 명령어로 추가되는 데이터는 그 데이터의 status가 Delayed, Boarding이고 좌석 수가 남아 있는 정보에 한 해 추가한다고 명시되어 있습니다.
<img width="251" alt="image" src="https://github.com/user-attachments/assets/46397cfd-794b-4482-80e7-f09714577b60">
그런데 ADD 명령어 설명의 상태 정보 업데이트 내용에서 
Cancelled->Boarding의 경우는 좌석 수를 감소 시키는 경우라고 명시해주셨는데 그렇게 되면 맨 위에 첨부한 사진의 상태 정보 설명에서 'Departure, Cancelled인 경우 더 이상 승객을 받지 않는다'는 내용과 맞지 않게 되는 것 같아서 질문 드립니다!
기존 closed된 issue에서 관련 질문에 대해 답변해주신 것을 확인했을 때는 문제 조건으로 생각하면 된다고 하신 것을 확인할 수 있었는데 과제 제안서 그대로 Cancelled->Boarding case도 좌석 수를 1 감소 시키는 경우로 생각하면 되는지 아니면 이에 대해서는 예외 처리 하면 될까요?
error 코드 출력 구현 자체와 문제 조건으로만 놓고 고려했을 때는 ADD의 error case를 제시해주신 4가지 경우를 제외한 나머지에 대해서만 출력하면 되는 것으로 생각하면 될까요??

**Comment by jisanggeun** [comment]
ADD 명령어 설명의 상태 정보 업데이트 내용에서 Cancelled->Boarding의 경우는 좌석 수를 감소 시키는 경우라고 명시해주셨는데 그렇게 되면 맨 위에 첨부한 사진의 상태 정보 설명에서 'Departure, Cancelled인 경우 더 이상 승객을 받지 않는다'는 내용과 맞지 않게 되는 것 같아서 질문 드립니다

--> 상태정보가 바뀌었기 때문에 승객을 받는 것이라고 생각하시면 되겠습니다.

따라서, 과제 제안서 그대로 Cancelled->Boarding case도 좌석 수를 1 감소 시키는 경우로 생각하면 됩니다.

좌석 수를 감소시키는 케이스는 다음과 같습니다.
Cancelled --> Boarding과 Boarding --> Boarding, Delayed --> Delayed

나머지 경우에는 좌석 수가 감소 안된다고 보시면 됩니다.

상태 업데이트는 Cancelled --> Boarding, Boarding --> Cancelled만 가능합니다.
(Delayed--> Boarding 불가능, Boarding-->Delayed 불가능, 이외 조건 불가능)
