### ISSUE TITLE
Manager 클래스에서 생성자의 인자를 고쳐도 되나요?

### ISSUE THREAD

**Issue by DwKwCs** [jisanggeun/DS_Project2_2024_2#5]
Manager 생성자의 인자 bpOrder에 상관없이 BpTree class에서 이미 BpTree의 차수가 3으로 초기화되어 있습니다.
그래서 Manager 생성자의 bpOrder 인자를 없애도 되는지 질문드립니다.

**Comment by jisanggeun** [comment]
bp차수가 3으로 고정된 이유는 b+ tree의 차수를 3으로 고정한다는 제안서 양식 때문입니다.
구현하실 때 3차로 구성하시면 지우셔도 될 것 같습니다.

**Comment by DwKwCs** [comment]
답변 감사합니다.
