### ISSUE TITLE
Manager.cpp 함수관련 질문드립니다.

### ISSUE THREAD

**Issue by zerobak13** [jisanggeun/DS_Project2_2024_2#6]
1. Manager.h에는 compare함수를 선언하는 부분이 없는데 Manager.cpp에 있는 compare함수를 사용하지 않아도 되나요?
2. ADD함수에서 인자를 추가하여 사용해도 되나요?

**Comment by jisanggeun** [comment]
1. 사용하지 않으셔도 됩니다. 

2. 인자 추가하셔서 사용하셔도 됩니다.

**Comment by zerobak13** [comment]
네 감사합니다.
