### ISSUE TITLE
BpTree 클래스에서 Search 관련 질문드립니다.

### ISSUE THREAD

**Issue by hanasol** [jisanggeun/DS_Project2_2024_2#7]
BrTree 클래스의 SearchDataNode 함수와 SearchRange 함수로 데이터 노드를 탐색 시에 Root 부터 비교하면서 내려오는 방식으로 구현해야 하는지 다른 방법을 사용해도 되는지 궁금합니다.

**Comment by jisanggeun** [comment]
index node를 참고해서 구현해주시면 될 것 같습니다.
