### ISSUE TITLE
ADD 명령어 문의드립니다.

### ISSUE THREAD

**Issue by DanielRho** [jisanggeun/DS_Project2_2024_2#9]
ADD 명령어를 통한 상태 정보 업데이트는
1. Cancelled → Boarding  
2. Boarding → Cancelled 
이렇게 두가지 경우에 한해서만 가능한 것인지 아니면
원래 존재하는 노드의 상태 정보가 Boarding, Cancelled, Departure, Delayed 어떠한 상태여도 새로 입력되는 상태 정보로 업데이트가 가능한지 궁금합니다.

**Comment by jisanggeun** [comment]
1. Cancelled → Boarding
2. Boarding → Cancelled 
두 가지 경우에 한해서만 가능합니다.
